/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WasteRouteImport } from './routes/waste'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as EdgeRouteImport } from './routes/edge'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CausalRouteImport } from './routes/causal'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const WasteRoute = WasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const EdgeRoute = EdgeRouteImport.update({
  id: '/edge',
  path: '/edge',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CausalRoute = CausalRouteImport.update({
  id: '/causal',
  path: '/causal',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/causal': typeof CausalRoute
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/edge': typeof EdgeRoute
  '/esg': typeof EsgRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/waste': typeof WasteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/causal': typeof CausalRoute
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/edge': typeof EdgeRoute
  '/esg': typeof EsgRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/waste': typeof WasteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/causal': typeof CausalRoute
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/edge': typeof EdgeRoute
  '/esg': typeof EsgRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/waste': typeof WasteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/causal'
    | '/dashboard'
    | '/digital-twin'
    | '/edge'
    | '/esg'
    | '/integrations'
    | '/inventory'
    | '/login'
    | '/production'
    | '/reports'
    | '/signup'
    | '/waste'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/causal'
    | '/dashboard'
    | '/digital-twin'
    | '/edge'
    | '/esg'
    | '/integrations'
    | '/inventory'
    | '/login'
    | '/production'
    | '/reports'
    | '/signup'
    | '/waste'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/causal'
    | '/dashboard'
    | '/digital-twin'
    | '/edge'
    | '/esg'
    | '/integrations'
    | '/inventory'
    | '/login'
    | '/production'
    | '/reports'
    | '/signup'
    | '/waste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CausalRoute: typeof CausalRoute
  DashboardRoute: typeof DashboardRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  EdgeRoute: typeof EdgeRoute
  EsgRoute: typeof EsgRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ProductionRoute: typeof ProductionRoute
  ReportsRoute: typeof ReportsRoute
  SignupRoute: typeof SignupRoute
  WasteRoute: typeof WasteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waste': {
      id: '/waste'
      path: '/waste'
      fullPath: '/waste'
      preLoaderRoute: typeof WasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edge': {
      id: '/edge'
      path: '/edge'
      fullPath: '/edge'
      preLoaderRoute: typeof EdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causal': {
      id: '/causal'
      path: '/causal'
      fullPath: '/causal'
      preLoaderRoute: typeof CausalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CausalRoute: CausalRoute,
  DashboardRoute: DashboardRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  EdgeRoute: EdgeRoute,
  EsgRoute: EsgRoute,
  IntegrationsRoute: IntegrationsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ProductionRoute: ProductionRoute,
  ReportsRoute: ReportsRoute,
  SignupRoute: SignupRoute,
  WasteRoute: WasteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
